/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.jackarain;

public class xproxy {
  public static String min_sdk_version() {
    return xproxyJNI.min_sdk_version();
  }

  public static String build_version() {
    return xproxyJNI.build_version();
  }

  public static int start(String config) {
    return xproxyJNI.start(config);
  }

  public static void stop() {
    xproxyJNI.stop();
  }

}
