/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.jackarain;

public class xproxyJNI {
  public final static native String min_sdk_version();
  public final static native String build_version();
  public final static native int start(String jarg1);
  public final static native void stop();
}
